### ISSUE TITLE
Enable "ucb_on_prem_hosting" In The Install Hook Of Other Hosting Modules 

### ISSUE THREAD

**Issue by alexfinnarn** [CuBoulder/express#2665]
<img width="1271" alt="screen shot 2018-06-27 at 5 29 15 pm" src="https://user-images.githubusercontent.com/3640707/42000777-cb6cd4be-7a2f-11e8-85b4-79057505b176.png">

I noticed this throughout the day and imagine it is another dependency issue where something was added to one hosting module but not another.

**Comment by kreynen** [comment]
This is related to https://github.com/CuBoulder/express/blob/dev/modules/features/cu_ldap/cu_ldap.module#L109

We actually have this issue in production now too until https://github.com/CuBoulder/express/issues/2598 is fixed

**Comment by alexfinnarn** [comment]
I still see no names on admin/people or admin/content so I think that it is a good idea to just enable `ucb_on_prem_hosting` in the install hook of `travis_hosting`. Otherwise, I don't think the hosting modules will be kept in sync. 

I would do the same for Pantheon and local hosting modules.

**Comment by alexfinnarn** [comment]
Since cu_users turns on LDAP, the hosting modules would have to switch to mixed-mode to log in any user where the site can't connect to LDAP.

Other than that, I'm not sure what else would be needed.
